### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by SoftCreatR**
The last release seems to be buggy. It has permission problems, takes a lot of CPU, has unnecessary dependencies, and so on.

This update aims to fix these issues, and also reduce the final image size to ~15M.

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
Running into these issues when trying to run in:
```
Starting initial definition download
ClamAV update process started at Tue Oct  4 08:27:32 2022
daily database available for download (remote version: 26678)
Testing database: '/var/lib/clamav/tmp.daf10e3b9b/clamav-ee7d4101a1161d0a526c2197966a651c.tmp-daily.cvd' ...
Database test passed.
daily.cvd updated (version: 26679, sigs: 2006662, f-level: 90, builder: raynman)
main database available for download (remote version: 62)
Testing database: '/var/lib/clamav/tmp.daf10e3b9b/clamav-3a2f4c910d83685d092f8861d58d8b15.tmp-main.cvd' ...
Database test passed.
main.cvd updated (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode database available for download (remote version: 333)
Testing database: '/var/lib/clamav/tmp.daf10e3b9b/clamav-3e71e297982a8fd0076eec12d4227377.tmp-bytecode.cvd' ...
Database test passed.
bytecode.cvd updated (version: 333, sigs: 92, f-level: 63, builder: awillia2)
WARNING: Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.sock: No such file or directory
```

**Comment by SoftCreatR** [comment]
That's not an issue. The warning is correct, because at the time of starting the update process, the clamav daemon isn't started. However, the database files are required for clamd to run, so (especially on first startup) it is required to run freshclam first.

**Comment by TorstenDittmann** [comment]
> That's not an issue. The warning is correct, because at the time of starting the update process, the clamav daemon isn't started.

Forgot to mention that it kills the container after that for me 😄

**Comment by SoftCreatR** [comment]
> > That's not an issue. The warning is correct, because at the time of starting the update process, the clamav daemon isn't started.
> 
> Forgot to mention that it kills the container after that for me 😄

Well then, maybe OOM? Because clamd requires a lot of it, unfortunately. At least when there is not enough CPU available and the process swaps.

**Comment by TorstenDittmann** [comment]
> > > That's not an issue. The warning is correct, because at the time of starting the update process, the clamav daemon isn't started.
> > 
> > 
> > Forgot to mention that it kills the container after that for me 😄
> 
> Well then, maybe OOM? Because clamd requires a lot of it, unfortunately. At least when there is not enough CPU available and the process swaps.


https://user-images.githubusercontent.com/1759475/193774409-fb995109-aa1b-47d5-81a3-e45b1f3e32a5.mov

Should have plenty left 👍🏻

Note, I am on M1 ARM - if thats makes a difference.

**Comment by SoftCreatR** [comment]
For some reason, it only runs freshclam, not the clamav service. However, on Travis, it works as expected, and also on my own server, where I tested it.

**Comment by SoftCreatR** [comment]
You are executing the Dockerfile itself without arguments. This only triggers freshclam, but doesn't start any service :) Run `docker-compose up` instead.

**Comment by TorstenDittmann** [comment]
Ahh! My bad, so it required 2 containers now?

Is there a way to avoid it?

**Comment by SoftCreatR** [comment]
I wouldn't avoid that. It's common practice to separate both processes. So a crash of freshclam wouldn't take down clamd, and vice versa.

However, it could be avoided, when necessary.

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
