### PR TITLE
Alpine-Release

### LINKED ISSUE #6: Convert base image to use alpine instead of ubuntu
We are looking for ways to make Appwrite Docker images smaller.

### PR DESCRIPTION
**Pull request by SoftCreatR**
- Switch from Ubuntu 18.04 to Alpine 3
- Add basic configuration from https://github.com/Cisco-Talos/clamav-devel/
- Remove docker-compose.yml
- Add periodical health check

Resolves #6

### CODE REVIEW

**Review by PedroCisnerosSantana — APPROVED** [review]

**Comment by eldadfux** [comment]
@SoftCreatR, I need you to revert the docker-compose file as it uses both as a usage example and for the CI tests

**Comment by eldadfux** [comment]
Please note, I have also made some minor changes in the master branch in my battle to make the tests pass

**Comment by eldadfux** [comment]
@SoftCreatR build is now failing:

```bash
ERROR: for clamav  Cannot start service clamav: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/start.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
The command "docker-compose up -d" failed and exited with 1 during .
```

https://travis-ci.com/github/appwrite/docker-clamav/builds/188516763

**Comment by SoftCreatR** [comment]
I know ;)

**Comment by SoftCreatR** [comment]
Seems to work now.

**Comment by eldadfux** [comment]
🚀

**Comment by SoftCreatR** [comment]
As for the test: What do you think about putting the EICAR test file into the container (e.g. `ADD http://www.eicar.org/download/eicar.com.txt /EICAR`) and execute `clamdscan` via Travis within the container?

**Comment by eldadfux** [comment]
I all for adding tests, but maybe it will be better if they will be completely external to the container and user `docker exec` or something similar to validate any change.

**Pull request merged**
