### PR TITLE
build and deploy script

### PR DESCRIPTION
**Pull request by lohanidamodar**

### CODE REVIEW

**Review by kodumbeats — APPROVED** [review]

**Comment by eldadfux** [comment]
Can we make the build run only on AMD? I wouldn't want to loose the ARM tests completely.

**Comment by kodumbeats** [comment]
I think this should do the trick:
```
deploy:
    on:
        tags: true
        condition: $TRAVIS_CPU_ARCH = amd64
```
> TRAVIS_CPU_ARCH: On multi-arch builds, this value indicates the CPU architecture the job is running on. Values are currently amd64, arm64, ppc64le and s390x.

Ref: https://docs.travis-ci.com/user/deployment-v2/conditional#condition
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by eldadfux** [comment]
@kodumbeats looks good, we should probably adopt the same solution for the Telegraf repo as well.

**Comment by lohanidamodar** [comment]
@eldadfux @kodumbeats pushed the fix as suggested

**Comment by eldadfux** [comment]
Tests are failing 😧

**Comment by lohanidamodar** [comment]
> Tests are failing

Restarted!

**Pull request merged**
