### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by SoftCreatR**
- Use Ubuntu 22.04 in travis
- Updated clamav configuration files
- Updated Dockerfile to use Alpine 3.16
- Pinned package versions in Dockerfile

Supersedes #19

### CODE REVIEW

**Review by eldadfux — COMMENTED** [review]
Changes look good, but test seems to fail.

**Comment by SoftCreatR** [comment]
I saw that. I guess, it's because of the dist that is used. Maybe `focal` does the trick. I'll check that.

**Comment by SoftCreatR** [comment]
Okay, the reason is, that I've picked the wrong package version for the version pinning.

**Comment by eldadfux** [comment]
Amazing work as always! ❤️

**Pull request merged**
